import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 常に認証状態を管理するのに必要
import SupabaseListener from "@/components/SupabaseListener";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "next-supabase-auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <SupabaseListener />
          <main className="flex-1 container max-w-screen-sm mx-auto px-1 py-5">
            {children}
          </main>
          <footer className="py-5">
            <div className="text-center text-sm">Copyright ©Ayumu Kubota</div>
          </footer>
        </div>
      </body>
    </html>
  );
}
