import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 常に認証状態を管理するのに必要
import SupabaseListener from "@/components/SupabaseListener";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "next-supabase-auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <div className="flex flex-col h-full">
          <SupabaseListener />
          <main className="flex-1 flex justify-center ">{children}</main>
        </div>
      </body>
    </html>
  );
}
